1) Create a python program to find duplicate files by content. User will input path and it will scan all directories, sub-   directories to find all duplicates files.
Delete the found duplicate file.

In [4]:
import os
import hashlib
def hs(input):
    byte_input=input.encode()
    hash_object=hashlib.sha256(byte_input)
    return hash_object.hexdigest()

#path = C:/Users/pvashishth/Desktop/New folder/
path=input("Enter path")
filelist = {}
print("The path of files which are removed are:-")
for root, dirs, files in os.walk(path):
    for file in files:
        #append the file name to the list
        x=os.path.join(root,file)
        l=open(x)
        a=l.read()
        l.close()
        a=hs(a)
        if a in filelist.keys():
            os.remove(x)
            print(x)
        else:
            filelist[a]=x

Enter pathC:/Users/pvashishth/Desktop/New folder/
The path of files which are removed are:-
C:/Users/pvashishth/Desktop/New folder/text_3.txt


2 )Generate random Password with exact length = 6, with minimum 1 uppercase, 2 lowercase, 2 digits, and remaining special characters.
Using these packages [random, strings]

In [9]:
import random
import string
lowercase=string.ascii_lowercase
uppercase=string.ascii_uppercase
digits=string.digits
l=[]
l.append(random.choice(uppercase))
for i in range(2):
    l.append(random.choice(lowercase))
for i in range(2):
    l.append(random.choice(digits))
l.append(random.choice(string.punctuation))
paragraph=''
while len(l)>0:
    c=random.choice(l)
    paragraph+=c
    l.remove(c)
print(paragraph)

7R~7oj


3) Create 2D array and update the same 2D array provided that every prime number position should be replaced by cube of the positioned number.

In [10]:
import numpy as np
import math

def isPrime(n):
    for i in range(2,(n//2)+1):
        if n%i==0:
            return False
    return True

l=[[2,3,4,66],
  [25,31,42,656],
  [222,43,47,646],
  [22,31,14,166]]
s=int(len(l))
arr=np.array(l).reshape(s,s)
print('Input:-')
print(arr)

for i in range(s):
    for j in range(s):
        xx=i*s+j
        x=arr[i][j]
        arr[i][j]=x*x*x if isPrime(xx) else x

print('Output:-')        
print(arr)


Input:-
[[  2   3   4  66]
 [ 25  31  42 656]
 [222  43  47 646]
 [ 22  31  14 166]]
Output:-
[[        8        27        64    287496]
 [       25     29791        42 282300416]
 [      222        43        47 269586136]
 [       22     29791        14       166]]


4) Python program to get the sum of every cubed value and its previous integer.

In [12]:
def isCube(n):
    if n**(1/3)==abs(n**(1/3)):
        return True
    return False
answer=0
for i in range(s):
    for j in range(s):
        answer+=arr[i][j] if isCube(arr[i][j]) else 0
print(answer)

552234310


5) Given two arrays, find their intersection.

In [13]:
import numpy as np
arr1=np.array([10,30,40,50,70])
arr2=np.array([20,30,50,60])
print(np.intersect1d(arr1,arr2))

[30 50]


6) Create a 7 x 7 2D array having only multiples of 7. And return the last element of the same.

In [14]:
arr = np.ones((7,7),"int64")

position=1
for i in range(7):
    for j in range(7):
        if i==0 and j==0:
            arr[0][0]=7
            position+=1
        else:
            arr[i][j]=7*position
            position+=1
            
print(arr)
print(arr[6][6])

[[  7  14  21  28  35  42  49]
 [ 56  63  70  77  84  91  98]
 [105 112 119 126 133 140 147]
 [154 161 168 175 182 189 196]
 [203 210 217 224 231 238 245]
 [252 259 266 273 280 287 294]
 [301 308 315 322 329 336 343]]
343


7) Checker Board Patten using Numpy:

In [15]:
x = np.ones((7, 5))
x[1::2, ::2] = 0
x[::2, 1::2] = 0
print(x)

[[1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]]


8) Create a given Matrix:
[ A, B, C, D E, F, G, H I, a, K, L M, N, o, P Q, R, S, T U, 0, W, O ]

Replace all the vowels by np.nan A, E, I, O U -- > np.nan Return the count of the missing values

In [17]:
import numpy as np
l=[[ 'A','B', 'C', 'D'],
   ['E', 'F', 'G', 'H' ],
   ['I', 'a', 'K', 'L' ],
   ['M', 'N', 'o', 'P' ],
   ['Q', 'R', 'S', 'T' ],
   ['U', '0', 'W', 'O' ]]
print(l)
def vowel(a):
    a=a.lower()
    if a in {'a','e','i','o','u'}:
        return True
    return False

count=0
for i in range(len(l)):
    for j in range(len(l[0])):
        if vowel(l[i][j]) :
            l[i][j]=np.nan
            count+=1

print(l)

print(count)

[['A', 'B', 'C', 'D'], ['E', 'F', 'G', 'H'], ['I', 'a', 'K', 'L'], ['M', 'N', 'o', 'P'], ['Q', 'R', 'S', 'T'], ['U', '0', 'W', 'O']]
[[nan, 'B', 'C', 'D'], [nan, 'F', 'G', 'H'], [nan, nan, 'K', 'L'], ['M', 'N', nan, 'P'], ['Q', 'R', 'S', 'T'], [nan, '0', 'W', nan]]
7
